version: "3"
services:
  app:
    build: .
    environment:
      DSN: host=db user=postgres password=jqKwlS9vN0mfm1v dbname=app sslmode=disable
      JWT_SECRET: SecretYouShouldHide
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: "jqKwlS9vN0mfm1v"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
volumes:
  db:
